name: Lint - hadolint
description: Run hadolint on all Dockerfiles

runs:
  using: composite
  steps:
    - name: Run hadolint
      shell: bash
      run: |
        docker run --rm \
          -v "$(pwd):/workdir" \
          -w /workdir \
          ghcr.io/yamnish/linter-hadolint:latest \
          sh -c 'find . \( -name "Dockerfile" -o -name "Dockerfile.*" \) -not -path "./.git/*" | xargs -r hadolint'
