name: Build linter images
description: Build all linter Docker images from platform-ci

runs:
  using: composite
  steps:
    - name: Build linter images
      shell: bash
      run: |
        docker compose -f "${{ github.action_path }}/../../../linters/docker-compose.yml" build
